language: python

python:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.1
  - 3.2
  - 3.3
  - pypy

install:
    pip install --use-mirrors cython

script:
  - python setup.py clean
  - python setup.py build_ext --inplace
  - make test

